apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zy603dn0w-go 
  janus-idp.io/tekton: zy603dn0w-go
  backstage.io/kubernetes-id: zy603dn0w-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zy603dn0w-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml